# syntax=docker/dockerfile:1.7-labs@sha256:b99fecfe00268a8b556fad7d9c37ee25d716ae08a5d7320e6d51c4dd83246894
FROM scratch AS build_outs
WORKDIR /monorepo/libraries/logs
COPY --from=libraries_logs-build --link --parents /monorepo/libraries/logs/build/**/* /monorepo/libraries/logs/.gradle/**/* /monorepo/libraries/logs/build.gradle.kts /monorepo/libraries/logs/settings.gradle.kts /monorepo/libraries/logs/gradle.properties /monorepo/libraries/logs/gradlew /monorepo/libraries/logs/gradle/wrapper/**/* /monorepo/libraries/logs/gradle/libs.versions.toml /
