services:
  guis_web-build:
    build:
      additional_contexts:
        guis_web-setup: service:guis_web-setup
        bayt-runtime: ../../../plugins/bayt
      context: ..
      dockerfile: .bayt/Dockerfile.build
      target: build
    image: bayt-guis_web-build:latest
