services:
  guis_web-integrate:
    build:
      additional_contexts:
        guis_web-build: service:guis_web-build
        bayt-runtime: ../../../plugins/bayt
      context: ..
      dockerfile: .bayt/Dockerfile.integrate
      target: integrate
    image: bayt-guis_web-integrate:latest
