services:
  guis_web-launch:
    build:
      additional_contexts:
        guis_web-build: service:guis_web-build
        workspaceroot-setup: service:workspaceroot-setup
      context: ..
      dockerfile: .bayt/Dockerfile.launch
      target: launch
    develop:
      watch:
      - action: sync
        path: .././
        target: /monorepo/guis/web/./
      - action: rebuild
        path: ../package.json
      - action: rebuild
        path: ../pnpm-lock.yaml
    image: bayt-guis_web-launch:latest
