services:
  guis_web-build_outs:
    build:
      context: ..
      dockerfile: .bayt/Dockerfile.build_outs
      target: build_outs
      additional_contexts:
        guis_web-build: service:guis_web-build
    image: bayt-guis_web-build_outs:latest
