services:
  guis_web-integrate:
    build:
      additional_contexts:
        bayt: ../../../plugins/bayt/runtime
        guis_web-build: service:guis_web-build
      context: ..
      dockerfile: .bayt/Dockerfile.integrate
      target: integrate
    image: bayt-guis_web-integrate:latest
