# syntax=docker/dockerfile:1.7-labs@sha256:b99fecfe00268a8b556fad7d9c37ee25d716ae08a5d7320e6d51c4dd83246894
FROM scratch AS build_outs
WORKDIR /monorepo/guis/web
COPY --from=guis_web-build --link --parents /monorepo/guis/web/.output/**/* /
