# syntax=docker/dockerfile:1.7-labs@sha256:b99fecfe00268a8b556fad7d9c37ee25d716ae08a5d7320e6d51c4dd83246894
FROM opensuse/leap:15.6@sha256:99c3ce36da52de669d5fd6663528438b0579cafa7efeab2e9e6d610a3c4b6c9e AS launch
WORKDIR /monorepo/guis/web
COPY --from=bonitao/lazybox:0.8.0@sha256:98414753b9ae2e90b096a1e3a9f7598ac2477e10fa3e5384083d9e29dde3c499 /lazybox/ /root/.local/share/lazybox/
ENV PATH=/root/.local/bin:/root/.local/share/lazybox/bin:$PATH
ENV MISE_TRUSTED_CONFIG_PATHS=/monorepo
COPY --from=guis_web-build --link --parents /monorepo/guis/web/.output/**/* /
COPY --from=workspaceroot-setup --link --parents /monorepo/.mise.toml /monorepo/mise.lock /monorepo/pnpm-lock.yaml /monorepo/pnpm-workspace.yaml /monorepo/package.json /monorepo/gradle/libs.versions.toml /monorepo/plugins/devserver/dind.sh /monorepo/.task/bayt/setup.hash /
RUN --mount=type=cache,target=/root/.local/share/pnpm/store,sharing=locked ["mise", "x", "--", "mise", "x", "--", "pnpm", "dev"]
COPY --link Taskfile.yml ./Taskfile.yml
COPY --link .bayt/Taskfile.yml .bayt/bayt.launch.json .bayt/init.gradle.kts ./.bayt/
EXPOSE 3000
