# syntax=docker/dockerfile:1.7-labs@sha256:b99fecfe00268a8b556fad7d9c37ee25d716ae08a5d7320e6d51c4dd83246894
FROM opensuse/leap:16.0@sha256:859560554b625c225fa767b76d61253d529b95d082c2d68579ad69168d5e3da7 AS launch
WORKDIR /monorepo/guis/web
COPY --from=bonitao/lazybox:0.8.3@sha256:c896a6836673d8fd217f6021a2522351fd82d580ed985159feb2f10373018e73 /lazybox/ /root/.local/share/lazybox/
ENV PATH=/root/.local/bin:/root/.local/share/lazybox/bin:$PATH
ENV MISE_TRUSTED_CONFIG_PATHS=/monorepo
RUN zypper -n install findutils=4.10.0-160000.2.2 which=2.23-160000.2.2
COPY --from=guis_web-build --link --parents /monorepo/guis/web/.output/**/* /
COPY --from=workspaceroot-setup --link --parents /monorepo/.mise.toml /monorepo/mise.lock /monorepo/pnpm-lock.yaml /monorepo/pnpm-workspace.yaml /monorepo/package.json /monorepo/gradle/libs.versions.toml /monorepo/plugins/devserver/dind.sh /monorepo/**/package.json /monorepo/.task/bayt/setup.hash /
COPY --link Taskfile.yml ./Taskfile.yml
COPY --link .bayt/Taskfile.yml .bayt/bayt.launch.json .bayt/init.gradle.kts ./.bayt/
EXPOSE 3000
CMD ["mise", "x", "--", "pnpm", "dev"]
