# syntax=docker/dockerfile:1.7-labs@sha256:b99fecfe00268a8b556fad7d9c37ee25d716ae08a5d7320e6d51c4dd83246894
FROM scratch AS build_srcs
WORKDIR /monorepo/guis/web
COPY --link --parents --exclude=node_modules/** --exclude=.nuxt/** --exclude=.output/** --exclude=dist/** --exclude=coverage/** --exclude=.bayt/** --exclude=.task/** --exclude=.git/** --exclude=**/*.test.* --exclude=**/*.spec.* --exclude=tests/** **/* ./
