version: '3'
includes:
  bayt:
    taskfile: ./.bayt/Taskfile.yml
    dir: ./
    optional: true
  libraries_xproto:
    taskfile: ../../libraries/xproto/Taskfile.yml
    dir: ../../libraries/xproto/
    optional: true
