#!/bin/sh

set -e

check_and_install() {
	command -v "$1" >/dev/null 2>&1 || {
		if command -v apt-get >/dev/null 2>&1; then
			sudo apt-get update && sudo apt-get install -y "$2"
		elif command -v yum >/dev/null 2>&1; then
			sudo yum install -y "$2"
		elif command -v apk >/dev/null 2>&1; then
			sudo apk add --no-cache "$2"
		elif command -v pacman >/dev/null 2>&1; then
			sudo pacman --noconfirm -Sy "$2"
		elif command -v brew >/dev/null 2>&1; then
			brew install "$2"
		else
			echo "Package manager not found. Please install $2 manually."
			exit 1
		fi
	}
}
check_and_install curl curl
check_and_install sudo sudo

install_pkgx() {
	os_type=$(uname)
	arch_type=$(uname -m)

	if [ "$os_type" = "Linux" ]; then
		if [ "$arch_type" = "x86_64" ]; then
			curl -L -o pkgx.tar.xz https://github.com/pkgxdev/pkgx/releases/download/v1.3.1/pkgx-1.3.1+linux+x86-64.tar.xz
		elif [ "$arch_type" = "aarch64" ]; then
			curl -L -o pkgx.tar.xz https://github.com/pkgxdev/pkgx/releases/download/v1.3.1/pkgx-1.3.1+linux+aarch64.tar.xz
		else
			echo "Unsupported architecture: $arch_type"
			exit 1
		fi
	elif [ "$os_type" = "Darwin" ]; then
		if [ "$arch_type" = "x86_64" ]; then
			curl -L -o pkgx.tar.xz https://github.com/pkgxdev/pkgx/releases/download/v1.3.1/pkgx-1.3.1+darwin+x86-64.tar.xz
		elif [ "$arch_type" = "arm64" ] || [ "$arch_type" = "aarch64" ]; then
			curl -L -o pkgx.tar.xz https://github.com/pkgxdev/pkgx/releases/download/v1.3.1/pkgx-1.3.1+darwin+aarch64.tar.xz
		else
			echo "Unsupported architecture: $arch_type"
			exit 1
		fi
	else
		echo "Unsupported OS type: $os_type"
		exit 1
	fi

	tar -xf pkgx.tar.xz
	sudo install -m 755 pkgx /usr/local/bin
	rm -f pkgx.tar.xz pkgx
}
command -v pkgx >/dev/null || install_pkgx
command -v nu >/dev/null || pkgx install nushell.sh@0.96.1
command -v just >/dev/null || pkgx install just.systems@1.29.1
