apiVersion: v1
kind: Service
metadata:
  name: pgrst-svc
spec:
  selector:
    app: pgrst-pod
  type: NodePort
  ports:
    - port: 28080
      targetPort : 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgrst-dpl
  labels:
    app: pgrst-dpl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgrst-pod
  template:
    metadata:
      labels:
        app: pgrst-pod
    spec:
      containers:
      - name: pgrst-cnt
        image: postgrest/postgrest:v10.1.2@sha256:79369c0cdf9d7112ed4e327bc1b80156be11575dd66fbda245077a2d13b803bc
        ports:
          - containerPort: 3000
        env:
          - name: POSTGRES_HOST
            value: "postgres-service"
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: password
          - name:  PGRST_DB_URI
            value: "postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST)/$(POSTGRES_DB)"
          - name: PGRST_DB_ANON_ROLE
            value: anon
        envFrom:
          - configMapRef:
              name: postgres-configuration
