apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    type: local
spec:
  storageClassName: standard  # for kind, docker-desktop needs hostpath instead
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle  # useful during a development cycle
  hostPath:
    path: /mnt1/postgres16-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  labels:
    type: local
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  volumeName: postgres-pv
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-statefulset
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16-alpine@sha256:a1efa4ac090c9065ecce437f78af3e4f6034311e04ab0055d5f8032e1fd03b60
        args: [ "-c", "wal_level=logical" ]
        envFrom:
        - configMapRef:
            name: postgres-configuration
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: password
        ports:
        - containerPort: 5432
          name: postgresdb
        volumeMounts:
        - name: postgres-volume-mount
          mountPath: /var/lib/postgresql/data
        readinessProbe:
          exec:
            command:
            - bash
            - "-c"
            - "psql -U$POSTGRES_USER -d$POSTGRES_DB -c 'SELECT 1'"
          initialDelaySeconds: 1
          timeoutSeconds: 1
        livenessProbe:
          exec:
            command:
            - bash
            - "-c"
            - "psql -U$POSTGRES_USER -d$POSTGRES_DB -c 'SELECT 1'"
          initialDelaySeconds: 1
          timeoutSeconds: 1
      volumes:
      - name: postgres-data
        emptyDir: {}
      - name: postgres-volume-mount
        persistentVolumeClaim:
          claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  ports:
  - port: 5432
    name: postgres
  type: NodePort
  selector:
    app: postgres
