services:
  services_tracker-tx-setup:
    build:
      additional_contexts:
        bayt-runtime: ../../../plugins/bayt
      context: ..
      dockerfile: .bayt/Dockerfile.setup
      target: setup
    image: bayt-services_tracker-tx-setup:latest
