services:
  services_tracker-tx-bayt:
    build:
      additional_contexts:
        libraries_xproto-bayt: service:libraries_xproto-bayt
        workspaceroot-bayt: service:workspaceroot-bayt
      context: ..
      dockerfile: .bayt/Dockerfile._bayt
      target: bayt
    image: bayt-services_tracker-tx-bayt:latest
