services:
  services_tracker-tx-integrate_srcs:
    build:
      additional_contexts:
        services_tracker-tx-build_srcs: service:services_tracker-tx-build_srcs
      context: ..
      dockerfile: .bayt/Dockerfile.integrate_srcs
      target: integrate_srcs
    image: bayt-services_tracker-tx-integrate_srcs:latest
