include:
- path: ./compose.setup.yaml
  required: false
- path: ./compose.build.yaml
  required: false
- path: ./compose.launch.yaml
  required: false
- path: ./compose.integrate.yaml
  required: false
- path: ./compose.release.yaml
  required: false
