# syntax=docker/dockerfile:1.7-labs@sha256:b99fecfe00268a8b556fad7d9c37ee25d716ae08a5d7320e6d51c4dd83246894
FROM scratch AS integrate_outs
WORKDIR /monorepo/services/tracker-tx
COPY --from=services_tracker-tx-integrate --link --parents /monorepo/services/tracker-tx/build/test-results-int/**/*.xml /
