include:
- path: ./compose.bayt.yaml
  required: false
services:
  build:
    extends:
      file: ./compose.build.yaml
      service: libraries_pbtables-build
  setup:
    extends:
      file: ./compose.setup.yaml
      service: libraries_pbtables-setup
  integrate:
    extends:
      file: ./compose.integrate.yaml
      service: libraries_pbtables-integrate
