# syntax=docker/dockerfile:1.7-labs@sha256:b99fecfe00268a8b556fad7d9c37ee25d716ae08a5d7320e6d51c4dd83246894
FROM scratch AS build_outs
WORKDIR /monorepo/libraries/pbtables
COPY --from=libraries_pbtables-build --link --parents /monorepo/libraries/pbtables/build/**/* /monorepo/libraries/pbtables/.gradle/**/* /monorepo/libraries/pbtables/build.gradle.kts /monorepo/libraries/pbtables/settings.gradle.kts /monorepo/libraries/pbtables/gradle.properties /monorepo/libraries/pbtables/gradlew /monorepo/libraries/pbtables/gradle/wrapper/**/* /monorepo/libraries/pbtables/gradle/libs.versions.toml /
