services:
  services_tracker-launch:
    build:
      additional_contexts:
        services_tracker-build: service:services_tracker-build
        libraries_logs-build: service:libraries_logs-build
        libraries_pbtables-build: service:libraries_pbtables-build
        libraries_xproto-build: service:libraries_xproto-build
        plugins_libstoml-build: service:plugins_libstoml-build
        plugins_jvm-build: service:plugins_jvm-build
        plugins_micronaut-build: service:plugins_micronaut-build
        workspaceroot-setup: service:workspaceroot-setup
      context: ..
      dockerfile: .bayt/Dockerfile.launch
      target: launch
      x-bake:
        cache-from:
        - type=registry,ref=registry.depot.dev/f5k5087x1b:tracker-bake-cache-v1-services_tracker-launch
        cache-to:
        - type=registry,ref=registry.depot.dev/f5k5087x1b:tracker-bake-cache-v1-services_tracker-launch,mode=min,image-manifest=true,oci-mediatypes=true
    image: bayt-services_tracker-launch:latest
