services:
  services_tracker-release-layers:
    build:
      additional_contexts:
        services_tracker-release-artifact: service:services_tracker-release-artifact
      context: ..
      dockerfile: .bayt/Dockerfile.release-layers
      target: release-layers
