services:
  services_tracker-setup_outs:
    build:
      context: ..
      dockerfile: .bayt/Dockerfile.setup_outs
      target: setup_outs
      additional_contexts:
        services_tracker-setup: service:services_tracker-setup
    image: bayt-services_tracker-setup_outs:latest
