services:
  services_tracker-release-artifact:
    build:
      additional_contexts:
        services_tracker-build: service:services_tracker-build
      context: ..
      dockerfile: .bayt/Dockerfile.release-artifact
      target: release-artifact
