secrets:
  docker_host:
    environment: BAYT_DOCKER_HOST
services:
  services_tracker-integrate:
    build:
      additional_contexts:
        bayt-runtime: service:bayt-runtime-stub
        services_tracker-build: service:services_tracker-build
        services_tracker-dindbox: service:services_tracker-dindbox
      context: ..
      dockerfile: .bayt/Dockerfile.integrate
      secrets:
      - docker_host
      target: integrate
    image: bayt-services_tracker-integrate:latest
    secrets:
    - docker_host
