services:
  services_tracker-build:
    build:
      additional_contexts:
        bayt-runtime: service:bayt-runtime-stub
        workspaceroot-setup: service:workspaceroot-setup
        libraries_logs-build: service:libraries_logs-build
        libraries_pbtables-build: service:libraries_pbtables-build
        libraries_xproto-build: service:libraries_xproto-build
        plugins_libstoml-build: service:plugins_libstoml-build
        plugins_jvm-build: service:plugins_jvm-build
        plugins_micronaut-build: service:plugins_micronaut-build
        services_tracker-setup: service:services_tracker-setup
      context: ..
      dockerfile: .bayt/Dockerfile.build
      target: build
