services:
  services_tracker-test-sources:
    build:
      context: ..
      dockerfile: .bayt/Dockerfile.test-sources
      target: test-sources
      x-bake:
        cache-from:
        - type=registry,ref=registry.depot.dev/f5k5087x1b:tracker-bake-cache-v1-services_tracker-test-sources
        cache-to:
        - type=registry,ref=registry.depot.dev/f5k5087x1b:tracker-bake-cache-v1-services_tracker-test-sources,mode=min,image-manifest=true,oci-mediatypes=true
    image: bayt-services_tracker-test-sources:latest
