# syntax=docker/dockerfile:1.7-labs@sha256:b99fecfe00268a8b556fad7d9c37ee25d716ae08a5d7320e6d51c4dd83246894
FROM opensuse/leap:16.0@sha256:859560554b625c225fa767b76d61253d529b95d082c2d68579ad69168d5e3da7 AS launch
WORKDIR /monorepo/services/tracker
COPY --from=bonitao/lazybox:0.8.2@sha256:334bf59aeae6ca3228d5308d33a02f47a00fc7ebcdcc38af5bab16613152bb82 /lazybox/ /root/.local/share/lazybox/
ENV PATH=/root/.local/bin:/root/.local/share/lazybox/bin:$PATH
ENV MISE_TRUSTED_CONFIG_PATHS=/monorepo
RUN zypper -n install findutils=4.10.0-160000.2.2 which=2.23-160000.2.2
COPY --from=services_tracker-build --exclude=.bayt/** --exclude=.git/** --link --parents /monorepo/services/tracker/**/* /
COPY --from=workspaceroot-setup --link --parents /monorepo/.mise.toml /monorepo/mise.lock /monorepo/pnpm-lock.yaml /monorepo/pnpm-workspace.yaml /monorepo/package.json /monorepo/gradle/libs.versions.toml /monorepo/plugins/devserver/dind.sh /monorepo/**/package.json /monorepo/.task/bayt/setup.hash /
COPY --from=libraries_logs-build --exclude=.bayt/** --exclude=.git/** --link --parents /monorepo/libraries/logs/**/* /
COPY --from=libraries_pbtables-build --exclude=.bayt/** --exclude=.git/** --link --parents /monorepo/libraries/pbtables/**/* /
COPY --from=libraries_xproto-build --exclude=.bayt/** --exclude=.git/** --link --parents /monorepo/libraries/xproto/**/* /
COPY --from=plugins_libstoml-build --exclude=.bayt/** --exclude=.git/** --link --parents /monorepo/plugins/libstoml/**/* /
COPY --from=plugins_jvm-build --exclude=.bayt/** --exclude=.git/** --link --parents /monorepo/plugins/jvm/**/* /
COPY --from=plugins_micronaut-build --exclude=.bayt/** --exclude=.git/** --link --parents /monorepo/plugins/micronaut/**/* /
RUN ["mise", "x", "--", "./gradlew", "--init-script", ".bayt/init.gradle.kts", "run"]
COPY --link Taskfile.yml ./Taskfile.yml
COPY --link .bayt/Taskfile.yml .bayt/bayt.launch.json .bayt/init.gradle.kts ./.bayt/
