# syntax=docker/dockerfile:1.7-labs@sha256:b99fecfe00268a8b556fad7d9c37ee25d716ae08a5d7320e6d51c4dd83246894
FROM scratch AS test-sources_outs
WORKDIR /monorepo/services/tracker
COPY --from=services_tracker-test-sources --link --parents /monorepo/services/tracker/src/it/**/* /monorepo/services/tracker/src/test/**/* /
