# syntax=docker/dockerfile:1.7-labs@sha256:b99fecfe00268a8b556fad7d9c37ee25d716ae08a5d7320e6d51c4dd83246894
FROM scratch AS test-sources
WORKDIR /monorepo/services/tracker
COPY --link --parents src/it/**/* src/test/**/* ./
COPY --link Taskfile.yml ./Taskfile.yml
COPY --link .bayt/Taskfile.yml .bayt/bayt.test-sources.json .bayt/init.gradle.kts ./.bayt/
