# syntax=docker/dockerfile:1.7-labs@sha256:b99fecfe00268a8b556fad7d9c37ee25d716ae08a5d7320e6d51c4dd83246894
FROM scratch AS build_outs
WORKDIR /monorepo/services/tracker
COPY --from=services_tracker-build --link --parents /monorepo/services/tracker/build/**/* /monorepo/services/tracker/.gradle/**/* /monorepo/services/tracker/build.gradle.kts /monorepo/services/tracker/settings.gradle.kts /monorepo/services/tracker/gradle.properties /monorepo/services/tracker/gradlew /monorepo/services/tracker/gradle/wrapper/**/* /monorepo/services/tracker/gradle/libs.versions.toml /
