apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: services_tracker-launch
profiles:
- activation:
  - command: dev
  name: bayt-dev
  build:
    artifacts:
    - docker:
        dockerfile: .bayt/Dockerfile.launch
      image: gcr.io/trash-362115/services.tracker
      context: ../
    local:
      useBuildkit: true
      concurrency: 64
    tagPolicy:
      gitCommit:
        variant: AbbrevCommitSha
