[settings]
lockfile = true
locked = true
experimental = true
paranoid = false
aqua.github_attestations = false
aqua.cosign = false
aqua.slsa = false
aqua.minisign = false

[tools]
"github:bufbuild/buf" = "1.66.1"
"github:cue-lang/cue" = "0.16.0"
"github:hairyhenderson/gomplate" = "5.0.0"
"github:go-task/task" = "v3.49.1"
"github:dapr/dapr" = "1.17.3"
"github:dapr/cli" = "1.17.0"
"github:redpanda-data/connect" = "4.46.0"
"github:nats-io/nats-server" = "2.12.6"

[tools."http:atlas"]
version = "0.38.0"
url = 'https://release.ariga.io/atlas/atlas-{{ os(macos="darwin") }}-{{ arch(x64="amd64") }}-v{{ version }}{% if os() == "windows" %}.exe{% endif %}'
