# vim: set filetype=yaml:---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: env-secret-store
spec:
  type: secretstores.local.env
  version: v1

---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pgstate
spec:
  type: state.postgresql
  version: v2
  metadata:
    - name: connectionString
      secretKeyRef:
        name: DATABASE_URL
        key: DATABASE_URL
    - name: outboxPublishPubsub
      value: "eventbus"
    - name: outboxPublishTopic
      value: "cloudevents"
auth:
  secretStore: env-secret-store

---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: eventbus
spec:
  type: pubsub.redis
  version: v1
  metadata:
    - name: redisHost
      value: redis:6379
    - name: redisPassword
      value: ""

---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: redis-streams-binding
spec:
  type: bindings.redis
  version: v1
  metadata:
    - name: redisHost
      value: redis:6379
    - name: redisPassword
      value: ""
    - name: direction
      value: "input"
    - name: stream
      value: "hello_durable_stream"
    - name: consumerGroup
      value: "dapr_event_handlers"
    - name: processingTimeout
      value: "15s"
    - name: redeliverInterval
      value: "60s"

---
apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: outbox-subscription
spec:
  pubsubname: eventbus
  topic: cloudevents
  routes:
    default: /inbox-sorter

---
apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: inbox-subscription
spec:
  pubsubname: eventbus
  topic: cloudevents
  routes:
    default: /inbox
---
apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: hello-events-subscription
spec:
  pubsubname: eventbus
  topic: hello_events
  routes:
    default: /dapr-hello-events
