# syntax=docker/dockerfile:1.7-labs@sha256:b99fecfe00268a8b556fad7d9c37ee25d716ae08a5d7320e6d51c4dd83246894
FROM plugins_omnishell-build AS integrate
WORKDIR /monorepo/plugins/omnishell
COPY --link --parents test/**/* ./
COPY --from=bayt-runtime --link . /monorepo/plugins/bayt/
ENV PATH=/monorepo/plugins/bayt/bin:${PATH}
RUN ["mise", "x", "--", "bun", "test"]
COPY --link Taskfile.yml ./Taskfile.yml
COPY --link .bayt/Taskfile.yml .bayt/Taskfile.integrate.yaml .bayt/bayt.integrate.json .bayt/init.gradle.kts ./.bayt/
