# syntax=docker/dockerfile:1.7-labs@sha256:b99fecfe00268a8b556fad7d9c37ee25d716ae08a5d7320e6d51c4dd83246894
FROM scratch AS ops_srcs
WORKDIR /monorepo/plugins/omnishell
COPY --link --parents compose.yaml .bayt/** Taskfile.yml ./
COPY --link --from=workspaceroot-ops_srcs /monorepo /monorepo
