/// <reference types="vite/client" />
import { createRootRoute, Outlet, HeadContent, Scripts } from "@tanstack/react-router"
import appCss from "../styles/app.css?url"
import { ThemeToggle } from "@/components/theme-toggle"

// Start MSW in development (browser only)
if (typeof window !== "undefined") {
  import("@/lib/msw").then(({ worker }) => {
    worker.start({ onUnhandledRequest: "bypass" })
  })
}

// Register PWA service worker (production only — sw.js generated by workbox-build)
if (typeof window !== "undefined") {
  import("@/lib/sw-register").then(({ registerServiceWorker }) => {
    registerServiceWorker()
  })
}

export const Route = createRootRoute({
  head: () => ({
    meta: [
      { charSet: "utf-8" },
      { name: "viewport", content: "width=device-width, initial-scale=1" },
      { title: "Omnishell App" },
      { name: "theme-color", content: "#000000" },
    ],
    links: [
      { rel: "stylesheet", href: appCss },
      { rel: "manifest", href: "/manifest.json" },
    ],
  }),
  component: RootComponent,
})

function RootComponent() {
  return (
    <html lang="en">
      <head>
        <HeadContent />
      </head>
      <body className="min-h-screen bg-background text-foreground antialiased">
        <div className="fixed top-2 right-2 z-[var(--z-dropdown)]">
          <ThemeToggle />
        </div>
        <Outlet />
        <Scripts />
      </body>
    </html>
  )
}
