# syntax=docker/dockerfile:1.7-labs@sha256:b99fecfe00268a8b556fad7d9c37ee25d716ae08a5d7320e6d51c4dd83246894
FROM scratch AS build_outs
WORKDIR /monorepo/plugins/micronaut
COPY --from=plugins_micronaut-build --link --parents /monorepo/plugins/micronaut/build/**/* /monorepo/plugins/micronaut/.gradle/**/* /monorepo/plugins/micronaut/build.gradle.kts /monorepo/plugins/micronaut/settings.gradle.kts /monorepo/plugins/micronaut/gradle.properties /monorepo/plugins/micronaut/gradlew /monorepo/plugins/micronaut/gradle/wrapper/**/* /monorepo/plugins/micronaut/gradle/libs.versions.toml /
