# syntax=docker/dockerfile:1.7-labs@sha256:b99fecfe00268a8b556fad7d9c37ee25d716ae08a5d7320e6d51c4dd83246894
FROM plugins_jvm-build AS setup
WORKDIR /monorepo/plugins/micronaut
COPY --link --parents gradle/wrapper/gradle-wrapper.properties ./
COPY --link --parents .mise.toml mise.lock ./
RUN ["mise", "install"]
COPY --link Taskfile.yml ./Taskfile.yml
COPY --link .bayt/Taskfile.yml .bayt/Taskfile.setup.yaml .bayt/bayt.setup.json .bayt/init.gradle.kts ./.bayt/
