apiVersion: run.cnrm.cloud.google.com/v1beta1
kind: RunService
metadata:
  name: guis-web
spec:
  ingress: "INGRESS_TRAFFIC_ALL"
  location: "us-central1"
  projectRef:
    external: projects/trash-362115
  template:
    timeout: "600s"
    containers:
      - image: gcr.io/trash-362115/guis.web
        ports:
        - name: http1
          containerPort: 8080
    scaling:
      maxInstanceCount: 2
---
# https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/793
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPartialPolicy
metadata:
  name: allow-all-users-to-invoke-services-tracker
spec:
  resourceRef:
    apiVersion: run.cnrm.cloud.google.com/v1beta1
    kind: RunService
    name: guis-web
  bindings:
    - members:
      - member: allUsers
      role: roles/run.invoker
