apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: ksops-generator
  annotations:
    config.kubernetes.io/function: |
        exec:
          path: ksops
files:
  - ./sql-password-secret.enc.yaml
  - ./crossplane-secret.enc.yaml
