apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
metadata:
    name: trash-newpostgres
spec:
    databaseVersion: POSTGRES_14
    region: us-central1
    settings:
        # https://issuetracker.google.com/issues/69109113#comment79
        activationPolicy: ALWAYS
        availabilityType: ZONAL
        diskSize: 15
        diskType: PD_HDD
        locationPreference:
            zone: us-central1-a
        tier: db-custom-1-3840
        ipConfiguration:
            # enablePrivatePathForGoogleCloudServices: true  // not available yet?
            authorizedNetworks:
                - name: all
                  value: 0.0.0.0/0
        databaseFlags:
            - name: cloudsql.logical_decoding
              value: "on"
            - name: cloudsql.iam_authentication
              value: "on"
---
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLDatabase
metadata:
    name: trash-tracker-db
spec:
    instanceRef:
        name: trash-newpostgres
---
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLUser
metadata:
    name: iris
spec:
    instanceRef:
        name: trash-newpostgres
    password:
        valueFrom:
          secretKeyRef:
            name: sql-secret
            key: password
---
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLUser
metadata:
    name: cloudrun-service-account
spec:
    resourceID: trackersa@trash-362115.iam
    instanceRef:
        name: trash-newpostgres
    type: CLOUD_IAM_SERVICE_ACCOUNT
