apiVersion: run.cnrm.cloud.google.com/v1beta1
kind: RunService
metadata:
  name: services-tracker
  annotations:
    # https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/832
    cnrm.cloud.google.com/deletion-policy: abandon
spec:
  ingress: "INGRESS_TRAFFIC_ALL"
  location: "us-central1"
  projectRef:
    external: projects/trash-362115
  template:
    timeout: "600s"
    containers:
      - image: gcr.io/trash-362115/services.tracker
        ports:
        - name: h2c
          containerPort: 50051
        env:
        - name: POSTGRES_USER
          valueSource:
            secretKeyRef:
              secretRef:
                external: projects/646949889529/secrets/neon-database-user
              versionRef:
                external: latest
        - name: POSTGRES_PASSWORD
          valueSource:
            secretKeyRef:
              secretRef:
                external: projects/646949889529/secrets/neon-database-password
              versionRef:
                external: latest
        - name: POSTGRES_JDBC_URL
          valueSource:
            secretKeyRef:
              secretRef:
                external: projects/646949889529/secrets/neon-jdbc-url
              versionRef:
                external: latest
        - name: OPENAI_KEY
          valueSource:
            secretKeyRef:
              secretRef:
                external: projects/646949889529/secrets/OPENAI_API_KEY
              versionRef:
                external: "2"
        - name: AUDIENCE_KEY
          valueSource:
            secretKeyRef:
              secretRef:
                external: projects/646949889529/secrets/AUDIENCE_KEY
              versionRef:
                external: latest
        - name: GOOGLE_PLACES_KEY
          valueSource:
            secretKeyRef:
              secretRef:
                external: projects/646949889529/secrets/GOOGLE_PLACES_KEY
              versionRef:
                external: latest
        - name: GEMINI_API_KEY
          valueSource:
            secretKeyRef:
              secretRef:
                external: projects/646949889529/secrets/GEMINI_API_KEY
              versionRef:
                external: latest
        - name: MICRONAUT_ENVIRONMENTS
          value: gcp
    scaling:
      maxInstanceCount: 2
---
# https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/793
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPartialPolicy
metadata:
  name: allow-all-users-to-invoke-services-tracker
spec:
  resourceRef:
    apiVersion: run.cnrm.cloud.google.com/v1beta1
    kind: RunService
    name: services-tracker
  bindings:
    - members:
      - member: allUsers
      role: roles/run.invoker
---
apiVersion: run.cnrm.cloud.google.com/v1beta1
kind: RunService
metadata:
  name: services-tracker-tx
  annotations:
    # https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/832
    cnrm.cloud.google.com/deletion-policy: abandon
spec:
  ingress: "INGRESS_TRAFFIC_ALL"
  location: "us-central1"
  projectRef:
    external: projects/trash-362115
  template:
    containers:
      - image: gcr.io/trash-362115/services.tracker-tx-gcp
        ports:
        - name: http1
          containerPort: 18080
        env:
        - name: GRPC_ADDRESS
          value: services-tracker-646949889529.us-central1.run.app
        - name: GRPC_PORT
          value: "443"
        - name: CLOUD_TLS
          value: "true"

    scaling:
      maxInstanceCount: 2
---
# https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/793
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPartialPolicy
metadata:
  name: allow-all-users-to-invoke-services-tracker-tx
spec:
  resourceRef:
    apiVersion: run.cnrm.cloud.google.com/v1beta1
    kind: RunService
    name: services-tracker-tx
  bindings:
    - role: roles/run.invoker
      members:
      - member: allUsers
---
# The bucket for storing the pictures taken by the Iris app
apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucket
metadata:
  name: trash-362115-pics
spec:
  location: "us-central1"
---
apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucketAccessControl
metadata:
  name: make-public-trash-362115-pics
spec:
  bucketRef:
    name: trash-362115-pics
  entity: allUsers
  role: READER
