#!/bin/sh
if [ /root/.dcm/pkgx.sh --help >/dev/null 2>&1 ]; then
	/root/.dcm/pkgx.sh "$@"
	exit $?
fi
curl -o ./pkgx --compressed -f --proto '=https' https://pkgx.sh/$(uname)/$(uname -m)
mkdir -p /usr/local/bin/ && install -m 755 pkgx /usr/local/bin && rm pkgx
/usr/local/bin/pkgx "$@"
EXIT_CODE=$?
mv -n /usr/local/bin/pkgx /root/.dcm/pkgx.sh || true
exit $EXIT_CODE
