# Eclipse Mosquitto MQTT broker.
FROM eclipse-mosquitto:2.0-openssl@sha256:6852da90a65dfff7aa3a1c8b249e92bb83c17ea8bbcce56bedff8707332a1a29

COPY services/mqtt/mosquitto.conf /mosquitto/config/mosquitto.conf
