# syntax=docker/dockerfile:1.7-labs@sha256:b99fecfe00268a8b556fad7d9c37ee25d716ae08a5d7320e6d51c4dd83246894
FROM scratch AS setup_outs
WORKDIR /monorepo/plugins/libstoml
COPY --from=plugins_libstoml-setup --link --parents /monorepo/plugins/libstoml/gradle/wrapper/gradle-wrapper.properties /monorepo/plugins/libstoml/.mise.toml /monorepo/plugins/libstoml/mise.lock /monorepo/plugins/libstoml/.task/bayt/setup.hash /
