services:
  libraries_xproto-ops:
    build:
      additional_contexts:
        workspaceroot-ops: service:workspaceroot-ops
        plugins_libstoml-ops: service:plugins_libstoml-ops
        plugins_jvm-ops: service:plugins_jvm-ops
        libraries_logs-ops: service:libraries_logs-ops
      context: ..
      dockerfile: .bayt/Dockerfile.ops
      target: ops
    image: bayt-libraries_xproto-ops:latest
