services:
  libraries_xproto-integrate:
    build:
      additional_contexts:
        bayt-runtime: ${BAYT_RUNTIME:-docker-image://bonitao/bayt:0.5.0@sha256:29447e97c3634b048e06fc39bab2d227128d6eb96a69b4560911499586830492}
        libraries_xproto-build: service:libraries_xproto-build
      context: ..
      dockerfile: .bayt/Dockerfile.integrate
      target: integrate
      x-bake:
        cache-from:
        - type=registry,ref=registry.depot.dev/f5k5087x1b:monorepo-bake-cache-v1-libraries_xproto-integrate
        cache-to:
        - type=registry,ref=registry.depot.dev/f5k5087x1b:monorepo-bake-cache-v1-libraries_xproto-integrate,mode=min,image-manifest=true,oci-mediatypes=true
    image: bayt-libraries_xproto-integrate:latest
