services:
  libraries_xproto-build:
    build:
      additional_contexts:
        workspaceroot-setup: service:workspaceroot-setup
        plugins_libstoml-build: service:plugins_libstoml-build
        libraries_logs-build: service:libraries_logs-build
        libraries_xproto-setup: service:libraries_xproto-setup
        bayt-runtime: ../../../plugins/bayt
      context: ..
      dockerfile: .bayt/Dockerfile.build
      target: build
      x-bake:
        cache-from:
        - type=registry,ref=registry.depot.dev/f5k5087x1b:monorepo-bake-cache-v1-libraries_xproto-build
        cache-to:
        - type=registry,ref=registry.depot.dev/f5k5087x1b:monorepo-bake-cache-v1-libraries_xproto-build,mode=min,image-manifest=true,oci-mediatypes=true
    image: bayt-libraries_xproto-build:latest
