services:
  libraries_xproto-ops:
    build:
      additional_contexts:
        workspaceroot-ops: service:workspaceroot-ops
        plugins_libstoml-ops: service:plugins_libstoml-ops
        plugins_jvm-ops: service:plugins_jvm-ops
        libraries_logs-ops: service:libraries_logs-ops
      context: ..
      dockerfile: .bayt/Dockerfile.ops
      target: ops
      x-bake:
        cache-from:
        - type=registry,ref=registry.depot.dev/f5k5087x1b:monorepo-bake-cache-v1-libraries_xproto-ops
        cache-to:
        - type=registry,ref=registry.depot.dev/f5k5087x1b:monorepo-bake-cache-v1-libraries_xproto-ops,mode=min,image-manifest=true,oci-mediatypes=true
    image: bayt-libraries_xproto-ops:latest
