services:
  libraries_xproto-descriptor_outs:
    build:
      context: ..
      dockerfile: .bayt/Dockerfile.descriptor_outs
      target: descriptor_outs
      additional_contexts:
        libraries_xproto-descriptor: service:libraries_xproto-descriptor
    image: bayt-libraries_xproto-descriptor_outs:latest
