services:
  libraries_xproto-bayt:
    build:
      additional_contexts:
        plugins_libstoml-bayt: service:plugins_libstoml-bayt
        plugins_jvm-bayt: service:plugins_jvm-bayt
        libraries_logs-bayt: service:libraries_logs-bayt
        workspaceroot-bayt: service:workspaceroot-bayt
      context: ..
      dockerfile: .bayt/Dockerfile._bayt
      target: bayt
    image: bayt-libraries_xproto-bayt:latest
