# syntax=docker/dockerfile:1.7-labs@sha256:b99fecfe00268a8b556fad7d9c37ee25d716ae08a5d7320e6d51c4dd83246894
FROM scratch AS integrate_srcs
WORKDIR /monorepo/libraries/xproto
COPY --link --parents src/it/**/*.java src/it/**/*.kt src/it/resources/**/* ./
COPY --link --from=libraries_xproto-build_srcs /monorepo /monorepo
