# syntax=docker/dockerfile:1.7-labs@sha256:b99fecfe00268a8b556fad7d9c37ee25d716ae08a5d7320e6d51c4dd83246894
FROM scratch AS setup_outs
WORKDIR /monorepo/libraries/xproto
COPY --from=libraries_xproto-setup --link --parents /monorepo/libraries/xproto/gradle/wrapper/gradle-wrapper.properties /monorepo/libraries/xproto/.mise.toml /monorepo/libraries/xproto/mise.lock /monorepo/libraries/xproto/.task/bayt/setup.hash /
