# syntax=docker/dockerfile:1.7-labs@sha256:b99fecfe00268a8b556fad7d9c37ee25d716ae08a5d7320e6d51c4dd83246894
FROM scratch AS build_outs
WORKDIR /monorepo/libraries/xproto
COPY --from=libraries_xproto-build --link --parents /monorepo/libraries/xproto/build/**/* /monorepo/libraries/xproto/.gradle/**/* /monorepo/libraries/xproto/build.gradle.kts /monorepo/libraries/xproto/settings.gradle.kts /monorepo/libraries/xproto/gradle.properties /monorepo/libraries/xproto/gradlew /monorepo/libraries/xproto/gradle/wrapper/**/* /monorepo/libraries/xproto/gradle/libs.versions.toml /
