# syntax=docker/dockerfile:1.7-labs@sha256:b99fecfe00268a8b556fad7d9c37ee25d716ae08a5d7320e6d51c4dd83246894
FROM scratch AS descriptor_outs
WORKDIR /monorepo/libraries/xproto
COPY --from=libraries_xproto-descriptor --link --parents /monorepo/libraries/xproto/out/xproto.desc.pb /
