# syntax=docker/dockerfile:1.7-labs@sha256:b99fecfe00268a8b556fad7d9c37ee25d716ae08a5d7320e6d51c4dd83246894
FROM scratch AS build_outs
WORKDIR /monorepo/plugins/jvm
COPY --from=plugins_jvm-build --link --parents /monorepo/plugins/jvm/build/**/* /monorepo/plugins/jvm/.gradle/**/* /monorepo/plugins/jvm/build.gradle.kts /monorepo/plugins/jvm/settings.gradle.kts /monorepo/plugins/jvm/gradle.properties /monorepo/plugins/jvm/gradlew /monorepo/plugins/jvm/gradle/wrapper/**/* /monorepo/plugins/jvm/gradle/libs.versions.toml /
