# syntax=docker/dockerfile:1.7-labs@sha256:b99fecfe00268a8b556fad7d9c37ee25d716ae08a5d7320e6d51c4dd83246894
FROM scratch AS bayt
WORKDIR /monorepo/plugins/jvm
COPY --link --parents .bayt/** Taskfile.yml compose.yaml ./
COPY --link --from=workspaceroot-bayt /monorepo /monorepo
COPY --link --from=plugins_libstoml-bayt /monorepo /monorepo
