# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
project_name: guis-web

before:
  hooks:
    - pnpm install --frozen-lockfile
    - pnpm exec dotenv -e .env.production -- pnpm exec nuxt build

builds:
  - skip: true

publishers:
  - name: firebase
    cmd: pnpm decrypt-creds && pnpm exec firebase deploy --message "{{ .Version }}"

release:
  disable: true
