say:
  build:
    do: "run-task bayt:build"
    use: "./tools.nu [run-task]"
  test:
    do: "run-task bayt:test"
    use: "./tools.nu [run-task]"
  integrate:
    args: "--bake"
  generate:
    rulemap:
      nuxt-prepare:
        cmds:
          - do: "pnpm nuxt prepare"
  lint:
    rulemap:
      auto-cue: null
      eslint:
        cmds:
          - do: "pnpm lint"
