apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: guis_web
build:
  tagPolicy:
    sha256: {}
  local:
    push: false
    tryImportMissing: false
    useBuildkit: true
    concurrency: 64
  artifacts:
    - image: gcr.io/trash-362115/guis.web
      context: ../..
      docker:
        dockerfile: guis/web/Dockerfile
        target: release

profiles:
- name: production
  build:
    platforms: ["linux/amd64"]
    local:
      push: true

test:
  - image: gcr.io/trash-362115/guis.web
    custom:
    - command: just integrate
      timeoutSeconds: 3000
